### ISSUE TITLE
Implement TEA for Generation 7

### ISSUE THREAD

**Issue by Cu3PO42** [Cu3PO42/KeySAVe#141]
The NTR debugger doesn't work with SuMo, as such a new solution needs to be written. It should probably integrate with #63.

**Comment by Cu3PO42** [comment]
According to a report by u/Fadx the debugger does in fact work when connected to the internet in Festival Plaza, this would suffice.

**Comment by roflpwnt** [comment]
You can get online working by disabling NFC in game.
send the command 
`write(0x3DFFD0, (0x00, 0x10, 0xA0, 0xE3), pid=0x??)`

Where `??` is the PID of `niji_loc`

**Comment by Cu3PO42** [comment]
According to reports I have heard so far, this only works for streaming - not the debugger, and causes disconnects as soon as you enter Festival Plaza. Either way that shouldn't matter too much if we can indeed connect while in Festival Plaza without this fix.

**Comment by Ketzaren** [comment]
Sorry to jump in here but I've been using NTR to run the Sun and Moon GTS bot Ledybot and it's able to connect and work just fine. I just tried using TEA because I was curious and it was able to connect after I was online in the plaza but it wouldn't allow me to initiate a trade dump. Let me know if you need any help gathering data or if there's something you would like me to try.
