### ISSUE TITLE
Persian-Alola incorrectly shown as Persian-Mega

### ISSUE THREAD

**Issue by Bobblybook** [Cu3PO42/KeySAVe#154]
As title states :)

**Comment by Cu3PO42** [comment]
I currently grab all form names for Generation 7 Pokémon form names from PKHeX, it appears it is wrong there. *sighs* After a quick look, I spotted a few more things that appear to be incorrect.

I guess I'll just have to go over all forms and fix everything by hand as I did for Generation 6. That was a large effort, though and I currently don't quite have time for that, so I'll have to postpone localization issues for a bit.

**Comment by Bobblybook** [comment]
Where are these mappings stored? I can probably go through them, would be tedious but only needs to be done once.

**Comment by Cu3PO42** [comment]
This is all in the Cu3PO42/KeySAVCoreJS project. There is a file called `localization/forms7.json` there. Scripts to generate the files are in, surprise, `scripts`. They take the path to the PKHeX source as a parameter on the command line, one would probably want to regenerate them first in case something was fixes since then.

If you really are interested in helping out with this, please join #KeySAVe on synIRC so we can discuss some specifics.
