### ISSUE TITLE
[Request] Dumping saves for Gen 7 physical copies (via Powersaves)

### ISSUE THREAD

**Issue by Faerina** [Cu3PO42/KeySAVe#156]
Hello Cu3PO42,

First off thank you so much for your awesome work. Keysave has been a lifesaver for me, helped me save the huge workload in breeding for perfect IV. Instead of having to hatch every single Egg and training them to 50 I can read a whole box of Egg all at once. It also helps me finding my shiny by showing its ESV. I can't imagine breeding without it!
Although I mainly use it and Powersaves for breeding purpose only, I know it also offers other helpful features.

Recently, with the new release of Pokemon Sun and Moon, I got my hand on it and stopped at Nursery because I want to breed a pokemon myself to adventure with me. The problem is, leveling them to calculate the ID is a hard work, not to mention the EV always messes up with the process so I have to take note for every gained EV. So far I have no luck in successfully breeding one. I haven't reached the fourth island yet, so no access to Pokemon Judge. Besides, there isn't any way to find out about their ESV. 

I tried to use the dumping with Powersaves save, but unfortunately the game is not yet supported. 
Would it be possible to request for a chance for us using the physical copy of Pokemon Sun and Moon to enjoy KeySave again? I love the amazing design and interface, but I would be grateful already if it's just a small box of text or something like old Keysave to show the info of Eggs and Pokemon, and I believe many who own the physical copies would appreciate it very muchly. Breeding would be so very difficult without it, and even more strenuous if we want a shiny.

I'm so sorry about the lengthy request, please forgive me if this is not the place for request. Thank you for reading this. I hope you have great day with your friends and family! @Cu3PO42

**Comment by Cu3PO42** [comment]
Hello Faerina,

thanks for the kind words, I appreciate them. Unfortunately, for reasons outlined in #144, it is currently impossible for me to add support for Powersaves backups of Generation 7 games without setting up a public 3DS crypto server. The latter does unfortunately entail a lot of work (and cost) and has potential legal consequences, so I won't be doing that.

For the time being I can only recommend getting a digital copy or access to homebrew (although before you do, please confirm that it does in fact work for accessing retail carts of Gen 7 since I have heard conflicting reports and cannot check myself).

Best regards,  
Cu3PO42
